name: bench_push
on: [push]
jobs:
  build:
    name: Benchmark (push)
    runs-on: ubuntu-latest
    env:
      GOBIN: /home/runner/go
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code 
      uses: actions/checkout@v1

    - name: Get dependencies
      run: | 
            go mod download
  
    - name: Benchmark (against HEAD~1)
      run: |
       go get golang.org/x/perf/cmd/benchstat
       echo $GOBIN
       echo $PATH
       echo "New Commit:"
       git log -1 --format="%H"
       go test -bench=. -benchtime=.75s -count=8 > $HOME/new.txt
       git reset --hard HEAD
       git checkout HEAD~1
       echo "Base Commit:"
       git log -1 --format="%H"
       go test -bench=. -benchtime=.75s -count=8 > $HOME/old.txt
       benchstat $HOME/old.txt $HOME/new.txt
